### ISSUE TITLE
Tasker support plans?

### ISSUE THREAD

**Issue by legostax** [xargsgrep/PortKnocker#19]
This app is awesome, and I use it all the time now.

Are there any plans to support Tasker in the near future?

**Comment by xargsgrep** [comment]
Hi, unfortunately I don't really have time to build new features for it anymore. PRs are welcome though :).

**Comment by legostax** [comment]
Alrighty, well I'm sure I'll have to learn the Android SDK at some point. Expect a PR then. ;)

If I figure out another way, I'll come back here and post for those who find this.
