### ISSUE TITLE
Request ipv6

### ISSUE THREAD

**Issue by MedVed007** [xargsgrep/PortKnocker#3]
Hi
will it be possible to allow using ipv6 address for host. Working name with AAA records, but not possible to enter ipv6 address.
Thank you

**Comment by TDFKAOlli** [comment]
Hi MedVed007,

the hostname does already support IPv6 addresses - in my understanding-, the only fix needed is allowing to enter colon in the hostname filter:
```
@@ -26,7 +26,7 @@ public class HostnameInputFilter implements InputFilter
         for (int i = start; i < end; i++)
         {
             char c = source.charAt(i);
-            if (!Character.isLetterOrDigit(c) && c != '.' && c != '-') return "";
+            if (!Character.isLetterOrDigit(c) && c != '.' && c != '-' && c != ':') return "";
         }
         return null;
     }

```
When I try with example IPv6 address I do get "Network unreachable" which indicates in principle the address is taken. I just don't have a proper IPv6 setup. You have to try yourself with that fix.

Cheers, TDFKAOlli

**Comment by MedVed007** [comment]
Hi, no problem to test it, just in which version it will be available in play?
Thanks

**Comment by TDFKAOlli** [comment]
As of Google-Android security all applications upload to play are signed with a private key. So only xargsgrep could upload a new version to Google playstore. Not sure if he is still active and could do this minor fix and upload. Or you build it yourself...

**Comment by xargsgrep** [comment]
merged and published to play store. thanks for the fix.
